okulSistem/Controllers/DersController.cs
using Microsoft.AspNetCore.Mvc;
using okulSistem.Data;
using okulSistem.Models;

namespace okulSistem.Controllers
{
    public class DersController : Controller
    {
        private readonly AppDbContext _db;
        
        public DersController(AppDbContext db) {
            _db = db;
        }
        public IActionResult DersSayfa()
        {
            IEnumerable<Ders> objDersList = _db.Ders;
            return View(objDersList);
        }
        public IActionResult Create() //GET
        {
            using (var context = new AppDbContext())
            {
                var dersler = context.Ders.ToList();
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Ders obj) //POST
        {   
            if (ModelState.IsValid) {
                var context = new AppDbContext();
                context.Ders.Add(obj);
                context.SaveChanges();
                TempData["success"] = "Category created succsessfully";
                return RedirectToAction("DersSayfa");
            }
            return View(obj);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var DersFromDB = _db.Ders.Find(id);

            if (DersFromDB == null)
            {
                return NotFound();
            }

            return View(DersFromDB);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Ders obj)
        {
            if (ModelState.IsValid)
            {
                var context = new AppDbContext();
                context.Ders.Update(obj);
                context.SaveChanges();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("DersSayfa");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var DersFromDB = _db.Ders.Find(id);

            if (DersFromDB == null)
            {
                return NotFound();
            }

            return View(DersFromDB);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var context = new AppDbContext();
            var b = context.Ders.FirstOrDefault(x => x.Id == id);
            context.Ders.Remove(b);
            context.SaveChanges();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("DersSayfa");

        }
    }
}

okulSistem/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using okulSistem.Data;
using okulSistem.Models;

namespace okulSistem.Controllers
{
    public class OgrenciController : Controller
    {
        private readonly AppDbContext _db;

        public OgrenciController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Ogrenci> objOgrenciList = _db.Ogrenci;
            return View(objOgrenciList);
        }
        public IActionResult Create() //GET
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Ogrenci obj) //POST
        {
            if (ModelState.IsValid)
            {
                var context = new AppDbContext();
                context.Ogrenci.Add(obj);
                context.SaveChanges();
                TempData["success"] = "Category created succsessfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var OgrencıFromDB = _db.Ogrenci.Find(id);

            if (OgrencıFromDB == null)
            {
                return NotFound();
            }

            return View(OgrencıFromDB);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Ogrenci obj)
        {
            if (ModelState.IsValid)
            {
                var context = new AppDbContext();
                context.Ogrenci.Update(obj);
                context.SaveChanges();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var OgrencıFromDB = _db.Ogrenci.Find(id);

            if (OgrencıFromDB == null)
            {
                return NotFound();
            }

            return View(OgrencıFromDB);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var context = new AppDbContext();
            var b = context.Ders.FirstOrDefault(x => x.Id == id);
            context.Ders.Remove(b);
            context.SaveChanges();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

okulSistem/Controllers/OgrenciDersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using okulSistem.Data;
using okulSistem.Models;
using System.Linq;

namespace okulSistem.Controllers
{
    public class OgrenciDersController : Controller
    {
        private readonly AppDbContext _db;
        public OgrenciDersController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<OgrenciDers> objOgrenciDersList = _db.OgrenciDers;
            return View(objOgrenciDersList);

        }
        public IActionResult Create() //GET
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OgrenciDers obj) //POST
        {
            if (ModelState.IsValid)
            {
                var context = new AppDbContext();
                context.OgrenciDers.Add(obj);
                context.SaveChanges();
                TempData["success"] = "Category created succsessfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var OgrenciDersFromDB = _db.OgrenciDers.Find(id);

            if (OgrenciDersFromDB == null)
            {
                return NotFound();
            }

            return View(OgrenciDersFromDB);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(OgrenciDers obj)
        {
            if (ModelState.IsValid)
            {
                var context = new AppDbContext();
                context.OgrenciDers.Update(obj);
                context.SaveChanges();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var OgrenciDersFromDB = _db.OgrenciDers.Find(id);

            if (OgrenciDersFromDB == null)
            {
                return NotFound();
            }

            return View(OgrenciDersFromDB);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var context = new AppDbContext();
            var b = context.Ders.FirstOrDefault(x => x.Id == id);
            context.Ders.Remove(b);
            context.SaveChanges();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");

        }

    }
}

okulSistem/Controllers/OkulYonetimController.cs
using Microsoft.AspNetCore.Mvc;
using okulSistem.Data;
using okulSistem.Models;

namespace okulSistem.Controllers
{
    public class OkulYonetimController : Controller
    {
        private readonly AppDbContext _db;

        public OkulYonetimController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<OkulYonetim> objOkulYonetimList = _db.OkulYonetim;
            return View(objOkulYonetimList);
        }
        public IActionResult Create() //GET
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OkulYonetim obj) //POST
        {
            if (ModelState.IsValid)
            {
                var context = new AppDbContext();
                context.OkulYonetim.Add(obj);
                context.SaveChanges();
                TempData["success"] = "Category created succsessfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var OkulYonetimFromDB = _db.OkulYonetim.Find(id);

            if (OkulYonetimFromDB == null)
            {
                return NotFound();
            }

            return View(OkulYonetimFromDB);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(OkulYonetim obj)
        {
            if (ModelState.IsValid)
            {
                var context = new AppDbContext();
                context.OkulYonetim.Update(obj);
                context.SaveChanges();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var OkulYonetimFromDB = _db.OkulYonetim.Find(id);

            if (OkulYonetimFromDB == null)
            {
                return NotFound();
            }

            return View(OkulYonetimFromDB);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var context = new AppDbContext();
            var b = context.Ders.FirstOrDefault(x => x.Id == id);
            context.Ders.Remove(b);
            context.SaveChanges();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

okulSistem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - okulSistem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/okulSistem.styles.css" asp-append-version="true" />
</head>
<body>
    <header> 
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand" >okulSistem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Ders</a>
                            <div class="dropdown-menu">
                                <a asp-controller="Ders" asp-action="Create" class="dropdown-item">Giriş</a>
                                <a asp-controller="Ders" asp-action="DersSayfa" class="dropdown-item">Liste</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Öğrenci</a>
                            <div class="dropdown-menu">
                                <a asp-controller="Ogrenci" asp-action="Create" class="dropdown-item">Giriş</a>
                                <a asp-controller="Ogrenci" asp-action="Index" class="dropdown-item">Liste</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Öğrenci-Ders</a>
                            <div class="dropdown-menu">
                                <a asp-controller="OgrenciDers" asp-action="Create" class="dropdown-item">Giriş</a>
                                <a asp-controller="OgrenciDers" asp-action="Index" class="dropdown-item">Liste</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Yönetim</a>
                            <div class="dropdown-menu">
                                <a asp-controller="OkulYonetim" asp-action="Create" class="dropdown-item">Giriş</a>
                                <a asp-controller="OkulYonetim" asp-action="Index" class="dropdown-item">Liste</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div id="div_footer">
                Okulsistem 2022 | Tüm Hakları Saklıdır.
                </div>
            </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>